server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        boot:
          context:
            config: DEBUG